### ISSUE TITLE
Map Genres To Cocktails

### ISSUE THREAD

**Issue by KAntBarr** [ucb-allstars-project-1/movie-cocktail-combo#5]
# Map Genres To Cocktails
create an object with genres as the keys and arrays of cocktails as the values

**Comment by solangeindaco** [comment]
I started to work in it

**Comment by solangeindaco** [comment]
I create a function getRandomDrinkByGenre(genre) that return a random Drink by genre. I made a function printRandomDrinks() to test the function. The result can be seen in the console log.

I create a function "getOrdinaryDrinks() " that initialize a list of drinks with an array of ordinary drinks from thecocktail API
